CREATE TABLE IF NOT EXISTS schema_versions (
    version integer PRIMARY KEY,
    applied_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO schema_versions(version) VALUES (1) ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS nodes (
    node_id text PRIMARY KEY,
    broker text NOT NULL,
    account_type text NOT NULL,
    display_name text NOT NULL DEFAULT '',
    source_kind text NOT NULL DEFAULT 'sqlite_migration',
    first_seen_at timestamptz NOT NULL DEFAULT now(),
    last_ingested_at timestamptz,
    UNIQUE (node_id, broker, account_type)
);

CREATE TABLE IF NOT EXISTS ingestion_batches (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id text NOT NULL,
    broker text NOT NULL,
    account_type text NOT NULL,
    source_path text NOT NULL,
    source_sha256 text NOT NULL,
    status text NOT NULL,
    row_counts_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    error_text text,
    started_at timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz,
    FOREIGN KEY (node_id, broker, account_type)
        REFERENCES nodes(node_id, broker, account_type)
);

CREATE TABLE IF NOT EXISTS runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id text NOT NULL,
    broker text NOT NULL,
    account_type text NOT NULL,
    source_id bigint NOT NULL,
    created_at text NOT NULL,
    source_dir text NOT NULL,
    output_dir text NOT NULL,
    generations integer NOT NULL,
    variants_per_seed integer NOT NULL,
    max_seeds integer NOT NULL,
    execute_backtests smallint NOT NULL,
    dry_run smallint NOT NULL,
    hidden smallint NOT NULL DEFAULT 0,
    config_json text NOT NULL DEFAULT '',
    UNIQUE (node_id, broker, account_type, source_id),
    FOREIGN KEY (node_id, broker, account_type)
        REFERENCES nodes(node_id, broker, account_type)
);

CREATE TABLE IF NOT EXISTS candidates (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id text NOT NULL,
    broker text NOT NULL,
    account_type text NOT NULL,
    source_id bigint NOT NULL,
    run_id bigint REFERENCES runs(id) ON DELETE CASCADE,
    source_run_id bigint NOT NULL,
    generation integer NOT NULL,
    seed_path text NOT NULL,
    set_path text NOT NULL,
    symbol text NOT NULL,
    target_symbol text NOT NULL,
    period text NOT NULL,
    family text NOT NULL,
    run_strategy text NOT NULL,
    mutated_keys text NOT NULL,
    timeframe_keys text NOT NULL DEFAULT '',
    mutation_details_json text NOT NULL DEFAULT '',
    missing_lot_keys text NOT NULL,
    policy text NOT NULL,
    report_path text,
    score double precision,
    accepted smallint,
    metrics_json text,
    status text NOT NULL,
    created_at text NOT NULL,
    UNIQUE (node_id, broker, account_type, source_id),
    FOREIGN KEY (node_id, broker, account_type)
        REFERENCES nodes(node_id, broker, account_type)
);

CREATE TABLE IF NOT EXISTS seed_scores (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id text NOT NULL,
    broker text NOT NULL,
    account_type text NOT NULL,
    source_id bigint,
    seed_path text NOT NULL,
    seed_mtime double precision NOT NULL,
    seed_size bigint NOT NULL,
    symbol text NOT NULL,
    period text NOT NULL,
    family text NOT NULL,
    run_strategy text NOT NULL,
    report_path text,
    score double precision,
    accepted smallint,
    metrics_json text,
    status text NOT NULL,
    active smallint NOT NULL DEFAULT 1,
    last_seen text NOT NULL,
    evaluated_at text,
    UNIQUE (node_id, broker, account_type, seed_path),
    FOREIGN KEY (node_id, broker, account_type)
        REFERENCES nodes(node_id, broker, account_type)
);

CREATE TABLE IF NOT EXISTS seed_overrides (
    node_id text NOT NULL,
    broker text NOT NULL,
    account_type text NOT NULL,
    seed_path text NOT NULL,
    symbol text NOT NULL DEFAULT '',
    period text NOT NULL DEFAULT '',
    updated_at text NOT NULL,
    PRIMARY KEY (node_id, broker, account_type, seed_path),
    FOREIGN KEY (node_id, broker, account_type)
        REFERENCES nodes(node_id, broker, account_type)
);

CREATE TABLE IF NOT EXISTS candidate_robustness (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id text NOT NULL,
    broker text NOT NULL,
    account_type text NOT NULL,
    candidate_id bigint REFERENCES candidates(id) ON DELETE CASCADE,
    source_candidate_id bigint NOT NULL,
    run_id bigint REFERENCES runs(id) ON DELETE CASCADE,
    source_run_id bigint NOT NULL,
    status text NOT NULL,
    report_path text,
    score double precision,
    accepted smallint,
    metrics_json text,
    from_date text NOT NULL DEFAULT '',
    to_date text NOT NULL DEFAULT '',
    positive_bonus double precision NOT NULL DEFAULT 70.0,
    negative_bonus double precision NOT NULL DEFAULT -70.0,
    evaluated_at text NOT NULL,
    UNIQUE (node_id, broker, account_type, source_candidate_id),
    FOREIGN KEY (node_id, broker, account_type)
        REFERENCES nodes(node_id, broker, account_type)
);

CREATE TABLE IF NOT EXISTS candidate_final_tick (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id text NOT NULL,
    broker text NOT NULL,
    account_type text NOT NULL,
    candidate_id bigint REFERENCES candidates(id) ON DELETE CASCADE,
    source_candidate_id bigint NOT NULL,
    run_id bigint REFERENCES runs(id) ON DELETE CASCADE,
    source_run_id bigint NOT NULL,
    status text NOT NULL,
    accepted smallint,
    ohlc_report_path text,
    real_tick_report_path text,
    ohlc_score double precision,
    real_tick_score double precision,
    ohlc_metrics_json text,
    real_tick_metrics_json text,
    similarity_json text,
    history_quality double precision,
    min_history_quality double precision NOT NULL DEFAULT 80.0,
    from_date text NOT NULL DEFAULT '',
    to_date text NOT NULL DEFAULT '',
    max_net_delta_pct double precision NOT NULL DEFAULT 35.0,
    max_pf_delta_pct double precision NOT NULL DEFAULT 35.0,
    max_dd_delta_pct double precision NOT NULL DEFAULT 35.0,
    max_trades_delta_pct double precision NOT NULL DEFAULT 35.0,
    evaluated_at text NOT NULL,
    UNIQUE (node_id, broker, account_type, source_candidate_id),
    FOREIGN KEY (node_id, broker, account_type)
        REFERENCES nodes(node_id, broker, account_type)
);

CREATE TABLE IF NOT EXISTS candidate_final_tick_6m (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id text NOT NULL,
    broker text NOT NULL,
    account_type text NOT NULL,
    candidate_id bigint REFERENCES candidates(id) ON DELETE CASCADE,
    source_candidate_id bigint NOT NULL,
    run_id bigint REFERENCES runs(id) ON DELETE CASCADE,
    source_run_id bigint NOT NULL,
    status text NOT NULL,
    accepted smallint,
    ohlc_report_path text,
    real_tick_report_path text,
    ohlc_score double precision,
    real_tick_score double precision,
    ohlc_metrics_json text,
    real_tick_metrics_json text,
    similarity_json text,
    history_quality double precision,
    min_history_quality double precision NOT NULL DEFAULT 80.0,
    from_date text NOT NULL DEFAULT '',
    to_date text NOT NULL DEFAULT '',
    max_net_delta_pct double precision NOT NULL DEFAULT 35.0,
    max_pf_delta_pct double precision NOT NULL DEFAULT 35.0,
    max_dd_delta_pct double precision NOT NULL DEFAULT 35.0,
    max_trades_delta_pct double precision NOT NULL DEFAULT 35.0,
    evaluated_at text NOT NULL,
    UNIQUE (node_id, broker, account_type, source_candidate_id),
    FOREIGN KEY (node_id, broker, account_type)
        REFERENCES nodes(node_id, broker, account_type)
);

CREATE TABLE IF NOT EXISTS generation_seed_selection (
    node_id text NOT NULL,
    broker text NOT NULL,
    account_type text NOT NULL,
    run_id bigint REFERENCES runs(id) ON DELETE CASCADE,
    source_run_id bigint NOT NULL,
    generation integer NOT NULL,
    rank integer NOT NULL,
    seed_path text NOT NULL,
    symbol text NOT NULL,
    period text NOT NULL,
    family text NOT NULL,
    run_strategy text NOT NULL,
    selection_score double precision NOT NULL,
    asset_weight double precision NOT NULL,
    timeframe_weight double precision NOT NULL,
    diversity double precision NOT NULL,
    fitness_probability double precision NOT NULL DEFAULT 0.0,
    fitness_weight double precision NOT NULL DEFAULT 0.0,
    fitness_evidence double precision NOT NULL DEFAULT 0.0,
    created_at text NOT NULL,
    PRIMARY KEY (node_id, broker, account_type, source_run_id, generation, rank),
    FOREIGN KEY (node_id, broker, account_type)
        REFERENCES nodes(node_id, broker, account_type)
);

CREATE TABLE IF NOT EXISTS portfolios (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id text NOT NULL,
    broker text NOT NULL,
    account_type text NOT NULL,
    source_id bigint NOT NULL,
    created_at text NOT NULL,
    name text NOT NULL DEFAULT '',
    type text NOT NULL DEFAULT '',
    portfolio_type text NOT NULL DEFAULT 'balanced',
    num_symbols integer NOT NULL DEFAULT 0,
    account_capital double precision NOT NULL DEFAULT 0,
    capital double precision NOT NULL DEFAULT 0,
    target_valley_dd_pct double precision NOT NULL DEFAULT 0,
    target_point_dd_pct double precision NOT NULL DEFAULT 0,
    target_valley_dd double precision NOT NULL DEFAULT 0,
    target_point_dd double precision NOT NULL DEFAULT 0,
    actual_valley_dd double precision NOT NULL DEFAULT 0,
    actual_point_dd double precision NOT NULL DEFAULT 0,
    valley_usage_pct double precision NOT NULL DEFAULT 0,
    point_usage_pct double precision NOT NULL DEFAULT 0,
    total_net_profit double precision NOT NULL DEFAULT 0,
    total_lot double precision NOT NULL DEFAULT 0,
    total_units integer NOT NULL DEFAULT 0,
    active_strategies integer NOT NULL DEFAULT 0,
    target_strategies integer NOT NULL DEFAULT 0,
    stop_reason text NOT NULL DEFAULT '',
    scale_factor double precision,
    binding_constraint text,
    portfolio_scope text NOT NULL DEFAULT 'full_history',
    target_month integer,
    metrics_json text,
    UNIQUE (node_id, broker, account_type, source_id),
    FOREIGN KEY (node_id, broker, account_type)
        REFERENCES nodes(node_id, broker, account_type)
);

CREATE TABLE IF NOT EXISTS portfolio_allocations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id text NOT NULL,
    broker text NOT NULL,
    account_type text NOT NULL,
    source_id bigint NOT NULL,
    portfolio_id bigint REFERENCES portfolios(id) ON DELETE CASCADE,
    source_portfolio_id bigint NOT NULL,
    variant_key text NOT NULL DEFAULT '',
    variant_label text NOT NULL DEFAULT '',
    set_id text NOT NULL,
    source_candidate_ref text NOT NULL DEFAULT '',
    candidate_id bigint REFERENCES candidates(id) ON DELETE SET NULL,
    symbol text NOT NULL,
    units integer NOT NULL,
    lot double precision NOT NULL,
    net_profit_contribution double precision NOT NULL,
    standalone_valley_dd double precision NOT NULL,
    standalone_point_dd double precision NOT NULL,
    set_path text,
    timeframe text,
    lot_size_step double precision,
    margin_required double precision NOT NULL DEFAULT 0,
    margin_pct double precision NOT NULL DEFAULT 0,
    margin_leverage double precision NOT NULL DEFAULT 0,
    margin_contract_size double precision NOT NULL DEFAULT 0,
    margin_price double precision NOT NULL DEFAULT 0,
    is_report_path text,
    oos_report_path text,
    UNIQUE (node_id, broker, account_type, source_id),
    FOREIGN KEY (node_id, broker, account_type)
        REFERENCES nodes(node_id, broker, account_type)
);

CREATE TABLE IF NOT EXISTS portfolio_decision_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id text NOT NULL,
    broker text NOT NULL,
    account_type text NOT NULL,
    source_id bigint NOT NULL,
    portfolio_id bigint REFERENCES portfolios(id) ON DELETE CASCADE,
    source_portfolio_id bigint NOT NULL,
    step integer NOT NULL,
    action text NOT NULL,
    set_id text,
    from_set_id text,
    to_set_id text,
    gain double precision NOT NULL,
    valley_cost double precision NOT NULL,
    point_cost double precision NOT NULL,
    score double precision NOT NULL,
    portfolio_net_profit_after double precision NOT NULL,
    portfolio_valley_dd_after double precision NOT NULL,
    portfolio_point_dd_after double precision NOT NULL,
    reason text NOT NULL,
    UNIQUE (node_id, broker, account_type, source_id),
    FOREIGN KEY (node_id, broker, account_type)
        REFERENCES nodes(node_id, broker, account_type)
);

CREATE TABLE IF NOT EXISTS portfolio_members (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id text NOT NULL,
    broker text NOT NULL,
    account_type text NOT NULL,
    source_id bigint NOT NULL,
    portfolio_id bigint REFERENCES portfolios(id) ON DELETE CASCADE,
    source_portfolio_id bigint NOT NULL,
    source_candidate_id bigint,
    candidate_id bigint REFERENCES candidates(id) ON DELETE SET NULL,
    set_path text NOT NULL,
    symbol text,
    period text,
    lot_multiplier double precision,
    lot double precision,
    lot_size_step double precision,
    standalone_dd double precision,
    quality_score double precision,
    combined_net_profit double precision,
    is_report_path text,
    oos_report_path text,
    variant_key text NOT NULL DEFAULT '',
    variant_label text NOT NULL DEFAULT '',
    UNIQUE (node_id, broker, account_type, source_id),
    FOREIGN KEY (node_id, broker, account_type)
        REFERENCES nodes(node_id, broker, account_type)
);

CREATE TABLE IF NOT EXISTS portfolio_quarantine (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id text NOT NULL,
    broker text NOT NULL,
    account_type text NOT NULL,
    source_id bigint,
    source_account_type text NOT NULL DEFAULT '',
    source_candidate_id bigint,
    candidate_id bigint REFERENCES candidates(id) ON DELETE SET NULL,
    set_path text NOT NULL,
    symbol text,
    timeframe text,
    reason text NOT NULL DEFAULT '',
    source_portfolio_id bigint,
    quarantined_at text NOT NULL,
    UNIQUE (node_id, broker, account_type, set_path),
    FOREIGN KEY (node_id, broker, account_type)
        REFERENCES nodes(node_id, broker, account_type)
);

CREATE TABLE IF NOT EXISTS portfolio_versions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id text NOT NULL,
    broker text NOT NULL,
    account_type text NOT NULL,
    source_id bigint NOT NULL,
    portfolio_id bigint REFERENCES portfolios(id) ON DELETE CASCADE,
    source_portfolio_id bigint NOT NULL,
    version_no integer NOT NULL,
    created_at text NOT NULL,
    reason text NOT NULL,
    snapshot_json bytea NOT NULL,
    UNIQUE (node_id, broker, account_type, source_id),
    UNIQUE (portfolio_id, version_no),
    FOREIGN KEY (node_id, broker, account_type)
        REFERENCES nodes(node_id, broker, account_type)
);

CREATE INDEX IF NOT EXISTS candidates_scope_run_idx
    ON candidates(node_id, broker, account_type, run_id);
CREATE INDEX IF NOT EXISTS candidates_scope_status_idx
    ON candidates(node_id, broker, account_type, status);
CREATE INDEX IF NOT EXISTS robustness_scope_status_idx
    ON candidate_robustness(node_id, broker, account_type, status);
CREATE INDEX IF NOT EXISTS final_tick_scope_status_idx
    ON candidate_final_tick(node_id, broker, account_type, status);
CREATE INDEX IF NOT EXISTS final_tick_6m_scope_status_idx
    ON candidate_final_tick_6m(node_id, broker, account_type, status);
CREATE INDEX IF NOT EXISTS seed_scores_scope_status_idx
    ON seed_scores(node_id, broker, account_type, status);
CREATE INDEX IF NOT EXISTS portfolios_scope_idx
    ON portfolios(node_id, broker, account_type, portfolio_scope);
