CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS configuration_documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id text NOT NULL REFERENCES nodes(node_id) ON DELETE CASCADE,
    broker text NOT NULL,
    account_type text NOT NULL,
    scope text NOT NULL CHECK (scope IN ('node', 'broker', 'account')),
    config_key text NOT NULL,
    relative_path text NOT NULL,
    media_type text NOT NULL DEFAULT 'application/octet-stream',
    revision integer NOT NULL,
    plaintext_sha256 text NOT NULL,
    byte_size bigint NOT NULL CHECK (byte_size >= 0),
    source_mtime_ns bigint,
    required boolean NOT NULL DEFAULT false,
    encrypted boolean NOT NULL DEFAULT false,
    content_bytes bytea,
    encrypted_content bytea,
    metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    verified_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (node_id, broker, account_type, config_key, revision),
    CHECK (
        (encrypted AND encrypted_content IS NOT NULL AND content_bytes IS NULL)
        OR
        (NOT encrypted AND content_bytes IS NOT NULL AND encrypted_content IS NULL)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS configuration_documents_one_active
    ON configuration_documents(node_id, broker, account_type, config_key)
    WHERE active;

CREATE INDEX IF NOT EXISTS configuration_documents_lookup
    ON configuration_documents(broker, account_type, scope, active);

CREATE TABLE IF NOT EXISTS terminal_profiles (
    node_id text NOT NULL REFERENCES nodes(node_id) ON DELETE CASCADE,
    broker text NOT NULL,
    account_type text NOT NULL,
    profile_index integer NOT NULL,
    name text NOT NULL DEFAULT '',
    enabled boolean NOT NULL DEFAULT true,
    mt5_path text NOT NULL DEFAULT '',
    data_dir text NOT NULL DEFAULT '',
    experts_root text NOT NULL DEFAULT '',
    ubs_ex5_file text NOT NULL DEFAULT '',
    portable boolean NOT NULL DEFAULT false,
    source_sha256 text NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (node_id, broker, account_type, profile_index)
);

CREATE INDEX IF NOT EXISTS terminal_profiles_broker_lookup
    ON terminal_profiles(broker, account_type, enabled);

CREATE TABLE IF NOT EXISTS broker_universe_symbols (
    node_id text NOT NULL REFERENCES nodes(node_id) ON DELETE CASCADE,
    broker text NOT NULL,
    account_type text NOT NULL,
    asset_group text NOT NULL,
    symbol text NOT NULL,
    position integer NOT NULL,
    source_sha256 text NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (node_id, broker, account_type, asset_group, symbol)
);

CREATE INDEX IF NOT EXISTS broker_universe_symbols_lookup
    ON broker_universe_symbols(broker, asset_group, symbol);

INSERT INTO schema_versions(version) VALUES (3) ON CONFLICT DO NOTHING;
