from __future__ import annotations


def fmt_num(val: float) -> str:
    return str(int(val)) if val == int(val) else f"{val:g}"


def fmt_num_str(s: str) -> str:
    try:
        return fmt_num(float(s))
    except ValueError:
        return s


UBS_SECTION_LABELS: dict[str, str] = {
    "CustomOptimization": "Optimizacion personalizada",
    "filters": "Filtros de trading",
    "spreadfilter": "Filtro de spread / slippage",
    "otherfilters": "Otros filtros",
    "Variable_Values": "Valores de variables (ATR)",
    "ST1_Entry": "Estrategia 1 - Entrada",
    "Trade_mg": "Gestion de salidas",
    "Trade_Exit_TrailSL": "Trailing Stop Loss",
    "Trade_Exit_TrailTP": "Trailing Take Profit",
    "BE_Exit": "Break-even",
    "HL_settings": "Trailing SL por High/Low",
    "TimeTL": "Trailing SL por tiempo",
    "MagicTrail": "MagicTrail",
    "LotSizeSettings": "Gestion de lotaje",
    "GMT_Settings": "Configuracion GMT",
    "NFP_FILTER": "Filtro NFP",
    "IR_FILTER": "Filtro Interest Rate",
    "CPI_FILTER": "Filtro CPI",
    "timefilter": "Horario de trading",
}


UBS_PARAM_DESCRIPTIONS: dict[str, str] = {
    "ShowInfoPanel": "Muestra el panel de informacion en el grafico",
    "UpdateInfoTesting": "Actualiza el panel de informacion durante backtesting",
    "InfoPanelSizeAdjust": "Multiplicador de tamano del panel de informacion",
    "EP": "Expected Profit objetivo (criterio de optimizacion personalizada)",
    "RF": "Recovery Factor objetivo (criterio de optimizacion personalizada)",
    "TR": "Target Return objetivo (criterio de optimizacion personalizada)",
    "SpreadFilter": "Activa el filtro de spread; bloquea entradas con spread excesivo",
    "MaxSpread": "Spread maximo permitido en pips para abrir operacion",
    "DistForSpreadFilter": "Distancia en pips para activar el filtro de spread",
    "setSL_TP_After_Entry": "Pone SL/TP despues del fill, no en la orden pendiente",
    "Virtual_expiration": "Usa expiracion virtual de ordenes (no la del broker)",
    "useVirtualStops": "Stops virtuales: 0=off, 1=SL virtual, 2=TP virtual, 3=ambos",
    "VirtualSL_Safety_Hardstop_dist": "Distancia del hard stop de seguridad para SL virtual (0=off)",
    "SetVSL_to_hardSL_sec_delay": "Segundos de delay antes de convertir SL virtual a hard SL",
    "ATRDefault": "Valor ATR por defecto (0 = usar ATR calculado del mercado)",
    "ATR_Period": "Periodo del ATR en barras",
    "ATR_Timeframe": "Timeframe para calcular el ATR (enum MT5)",
    "DefaultValue": "Valor por defecto para variables internas",
    "AllowBuyTrades": "Permite operaciones largas (compra)",
    "AllowSellTrades": "Permite operaciones cortas (venta)",
    "ST1_Timeframe": "Timeframe de la estrategia 1 (0 = timeframe del grafico)",
    "Entry_Timing": "Modo de timing de entrada (enum MT5)",
    "ST1_HL_strength_L": "Barras a la izquierda del pivot para validar High/Low",
    "ST1_HL_strength_R": "Barras a la derecha del pivot para validar High/Low",
    "ST1_countback": "Numero de barras hacia atras para buscar el High/Low de entrada",
    "ST1_MinDist_to_HL": "Distancia minima del precio actual al H/L en pips",
    "ST1_MinDist_to_HL_percentage": "Distancia minima al H/L como porcentaje (0=desactivado)",
    "ST1_UpDiff": "Offset sobre el High para la entrada en pips (negativo = dentro del rango)",
    "ST1_DownDiff": "Offset bajo el Low para la entrada en pips (negativo = dentro del rango)",
    "ST1_MaxPendingOrders": "Maximo de ordenes pendientes simultaneas",
    "MaxTrades": "Maximo de operaciones abiertas simultaneas",
    "MinDist_orders": "Distancia minima entre ordenes pendientes en pips",
    "ST1_Expiration_hours": "Tiempo de expiracion de ordenes pendientes en horas",
    "EA_MagicNumber": "Numero magico del EA; identifica sus operaciones en el broker",
    "EA_Comment": "Comentario que aparece en cada operacion abierta",
    "Exit_Timing": "Modo de timing de salida (enum MT5)",
    "UseEveryTick": "Calcula salidas en cada tick (false = solo al cierre de barra)",
    "Exit_stop": "Tamano del Stop Loss en pips",
    "Exit_limit": "Tamano del Take Profit en pips",
    "Exit_TrailSL_size": "Distancia del Trailing SL en pips",
    "Exit_TrailSL_Start": "Beneficio en pips para activar el Trailing SL (0=inmediato)",
    "Exit_TrailSL_Stop": "Nivel de stop minimo para el Trailing SL en pips",
    "Exit_TrailSL_step": "Paso de ajuste del Trailing SL",
    "Exit_TrailTP_size": "Distancia del Trailing TP en pips (0=desactivado)",
    "Exit_TrailTP_Start": "Beneficio en pips para activar el Trailing TP",
    "Exit_BE_start": "Beneficio en pips para mover SL a break-even (0=off)",
    "Exit_BE_extra_pips": "Pips extra por encima del break-even al mover el SL",
    "Exit_HL_UseBE": "Usa logica break-even para el Trailing SL por H/L",
    "Exit_HL_trailingSL_timeframe": "Timeframe para los pivots del Trailing SL por H/L",
    "Exit_HL_countback": "Barras hacia atras para buscar pivots H/L trailing",
    "Exit_HL_trailingSL_candles_LEFT": "Barras a la izquierda del pivot H/L trailing",
    "Exit_HL_trailingSL_candles_RIGHT": "Barras a la derecha del pivot H/L trailing",
    "Exit_HL_TrailingSL_MinDist": "Distancia minima para que cambie el H/L trailing SL",
    "Exit_HL_Minimum_Dist_For_Change": "Distancia minima de beneficio antes de mover el SL",
    "Exit_HL_trailingSL_extra_distance": "Buffer extra para el Trailing SL por H/L",
    "Exit_TrailSL_after_X_Minutes": "Minutos en operacion para activar trailing por tiempo (0=off)",
    "Exit_TrailSL_after_X_Minutes_size": "Tamano del Trailing SL cuando se activa por tiempo",
    "Exit_MagicTrail_Mode": "MagicTrail: 0=off, 1=solo SL, 2=SL+TP",
    "Exit_MagicTrail_start": "Nivel de activacion del MagicTrail (pips de beneficio)",
    "Exit_MagicTrail_delay": "Delay en barras antes de que MagicTrail ajuste",
    "Exit_MagicTrail_size": "Tamano de trailing del MagicTrail",
    "Exit_MagicTrail_BE_extra_pips": "Pips extra de break-even para MagicTrail",
    "Exit_MagicTrail_Adjust_after_X_Minutes": "Ajusta MagicTrail despues de X minutos (0=off)",
    "Exit_MagicTrail_Adjust_after_X_Minutes_start": "Nivel de inicio para ajuste por tiempo de MagicTrail",
    "LotsAdjustMinChangePercent": "Cambio minimo en % para reajustar tamano de lote",
    "Risk": "Modo lotaje: 0=fijos, 1=% riesgo/op, 2=lote por balance, 3=manual",
    "StartLots": "Tamano de lote fijo (Risk=0)",
    "Manual_RiskPerTrade": "Porcentaje de riesgo por operacion (Risk=1)",
    "LotPerBalance_step": "Incremento de balance para sumar 0.01 lote (Risk=2)",
    "MaxLots": "Tamano maximo de lote permitido",
    "UseEquity": "Usa equidad en lugar de balance para calcular lotes",
    "OnlyUp": "Solo incrementa lote, nunca reduce durante la sesion",
    "CheckMargin": "Verifica margen disponible antes de abrir operacion",
    "Broker_GMT_OFFSET_Summer": "Offset GMT del broker en horario de verano (DST)",
    "Broker_GMT_OFFSET_Winter": "Offset GMT del broker en horario de invierno",
    "AutoGMT": "Deteccion automatica del offset GMT del broker",
    "EnableNFP_Filter": "Activa pausa de trading durante NFP (Non-Farm Payroll)",
    "NFP_CloseOpenTrades": "Cierra operaciones abiertas antes del NFP",
    "NFP_ClosePendingOrders": "Cancela ordenes pendientes antes del NFP",
    "NFP_MinutesBefore": "Minutos antes del NFP para detener trading",
    "NFP_MinutesAfter": "Minutos despues del NFP para reanudar trading",
    "EnableIR_Filter": "Activa pausa de trading durante anuncio de tipos de interes",
    "IR_CloseOpenTrades": "Cierra operaciones abiertas antes del anuncio IR",
    "IR_ClosePendingOrders": "Cancela ordenes pendientes antes del anuncio IR",
    "IR_MinutesBefore": "Minutos antes del anuncio IR para detener trading",
    "IR_MinutesAfter": "Minutos despues del anuncio IR para reanudar",
    "EnableCPI_Filter": "Activa pausa de trading durante publicacion del CPI",
    "CPI_CloseOpenTrades": "Cierra operaciones abiertas antes del CPI",
    "CPI_ClosePendingOrders": "Cancela ordenes pendientes antes del CPI",
    "CPI_MinutesBefore": "Minutos antes del CPI para detener trading",
    "CPI_MinutesAfter": "Minutos despues del CPI para reanudar",
    "UseTradingTimeZones": "Activa filtro de horario de trading por dias/horas",
    "KillPending": "Cancela ordenes pendientes fuera del horario permitido",
    "KillOpen": "Cierra operaciones abiertas fuera del horario permitido",
    "Time_Source": "Fuente de tiempo: 0=broker, 1=local, 2=servidor",
    "MondayStart": "Hora de inicio de trading los lunes (HH:MM)",
    "MondayEnd": "Hora de fin de trading los lunes (HH:MM)",
    "TuesdayStart": "Hora de inicio de trading los martes (HH:MM)",
    "TuesdayEnd": "Hora de fin de trading los martes (HH:MM)",
    "WednesdayStart": "Hora de inicio de trading los miercoles (HH:MM)",
    "WednesdayEnd": "Hora de fin de trading los miercoles (HH:MM)",
    "ThursdayStart": "Hora de inicio de trading los jueves (HH:MM)",
    "ThursdayEnd": "Hora de fin de trading los jueves (HH:MM)",
    "FridayStart": "Hora de inicio de trading los viernes (HH:MM)",
    "FridayEnd": "Hora de fin de trading los viernes (HH:MM)",
    "SaturdayStart": "Hora de inicio de trading los sabados (HH:MM)",
    "SaturdayEnd": "Hora de fin de trading los sabados (HH:MM)",
    "SundayStart": "Hora de inicio de trading los domingos (HH:MM)",
    "SundayEnd": "Hora de fin de trading los domingos (HH:MM)",
}
